# Nixpacks Configuration for Railway Deployment
# Properly configure paths for backend directory structure

[start]
cmd = "cd /app/backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"

[variables]
PYTHONPATH = "/app/backend"
PYTHONUNBUFFERED = "1" 
PYTHONDONTWRITEBYTECODE = "1"
PORT = "8000"
ENVIRONMENT = "production"
