# Nixpacks Configuration for Railway Deployment
# Minimal configuration - let NIXPACKS auto-detect everything

[start]
cmd = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"

[variables]
PORT = "8000"
