# Nixpacks Configuration for Railway Deployment
# WeasyPrint system dependencies using Railway's aptPkgs

[phases.setup]
aptPkgs = [
    # Core WeasyPrint system dependencies
    "libgobject-2.0-0",
    "libcairo2", 
    "libpango-1.0-0",
    "libgdk-pixbuf2.0-0",
    "libffi-dev",
    # Additional libraries for full WeasyPrint support
    "libharfbuzz0b",
    "libfribidi0",
    "fontconfig",
    "libfreetype6",
    "libjpeg62-turbo",
    "libpng16-16",
    "zlib1g",
    "libxml2",
    "libxslt1.1"
]

[start]
cmd = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"

[variables]
PORT = "8000"
