# Nixpacks Configuration for Railway Deployment
# Simplified configuration to let NIXPACKS auto-detect Python project

[start]
cmd = "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"

[variables]
PYTHONPATH = "/app/backend:/app"
PYTHONUNBUFFERED = "1" 
PYTHONDONTWRITEBYTECODE = "1"
PORT = "8000"
ENVIRONMENT = "production"
