# Nixpacks Configuration for Railway Deployment
# Comprehensive WeasyPrint system dependencies

[phases.setup]
aptPkgs = [
    # Core WeasyPrint dependencies
    "libgobject-2.0-0",
    "libcairo2", 
    "libpango-1.0-0",
    "libpangocairo-1.0-0",
    "libgdk-pixbuf2.0-0",
    "libffi-dev",
    # Image and font support
    "libjpeg-dev",
    "libpng-dev", 
    "libxml2",
    "libxml2-dev",
    "libxslt1-dev",
    "libz-dev",
    "libfontconfig1",
    "libharfbuzz-bin",
    "libfribidi-bin",
    # Additional libraries for text rendering
    "libglib2.0-0",
    "libcairo-gobject2",
    "libpangoft2-1.0-0",
    "fontconfig-config",
    # Development headers needed for compilation
    "libglib2.0-dev",
    "libcairo2-dev",
    "libpango1.0-dev",
    "libgdk-pixbuf2.0-dev"
]

[start]
cmd = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"

[variables]
PORT = "8000"
