# Nixpacks Configuration for Railway Deployment
# WeasyPrint with comprehensive dependencies

[phases.setup]
# All required WeasyPrint system dependencies
nixPkgs = [
    "...",
    "cairo",
    "pango", 
    "gdk-pixbuf",
    "glib",
    "gobject-introspection",
    "harfbuzz",
    "fontconfig",
    "freetype",
    "libffi"
]

[start]
cmd = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"

[variables]
LD_LIBRARY_PATH = "/nix/var/nix/profiles/default/lib"
GI_TYPELIB_PATH = "/nix/var/nix/profiles/default/lib/girepository-1.0"