# Nixpacks Configuration for Railway Deployment
# Simple configuration for WeasyPrint

[phases.setup]
# WeasyPrint system dependencies
nixPkgs = ["...", "cairo", "pango", "gdk-pixbuf", "libffi"]

[start]
cmd = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"